gem "github-pages", group: :jekyll_plugins

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag


title: Prakhar Gupta
description: Learning the future of robotics. :)
author: Prakhar Gupta
email: prakhag@clemson.edu

header_pages:
  - _pages/home.md
  - _pages/projects.md

include:
  - _pages


# Minima social links
linkedin_username: prakharkalyangupta
github_username:  pgupta2050
